#!/usr/bin/env python3
"""
Local marginal effects generator for PS0–PS3 (Ordered Logit with 4 categories).

Reads from each scenario folder:
  - bayesian_sem_inference_data.nc (required)
  - processed_data.pkl (optional, used to get dummy column names)

Outputs (deterministic overwrite):
  output_dir/
    marginal_effects_long_<scenario>.csv
    marginal_effects_long_all_scenarios.csv

Marginal effect definition:
  baseline eta0 = baseline_eta (default 0)
  counterfactual eta1 = eta0 + step * beta_j
  ME_k = P(Y=k|eta1) - P(Y=k|eta0), per draw.
"""

import argparse
from pathlib import Path
import pickle
import numpy as np
import pandas as pd

import arviz as az


# ----------------------------
# Math helpers
# ----------------------------
def sigmoid(x: np.ndarray) -> np.ndarray:
    return 1.0 / (1.0 + np.exp(-x))


def ordered_logit_probs(cutpoints: np.ndarray, eta: np.ndarray) -> np.ndarray:
    """
    cutpoints: (n_draws, 3)
    eta:       (n_draws,)
    returns:   (n_draws, 4)
    """
    eta = np.asarray(eta).reshape(-1, 1)
    c1 = cutpoints[:, 0:1]
    c2 = cutpoints[:, 1:2]
    c3 = cutpoints[:, 2:3]

    p0 = sigmoid(c1 - eta)
    p1 = sigmoid(c2 - eta) - sigmoid(c1 - eta)
    p2 = sigmoid(c3 - eta) - sigmoid(c2 - eta)
    p3 = 1.0 - sigmoid(c3 - eta)
    P = np.concatenate([p0, p1, p2, p3], axis=1)

    P = np.clip(P, 0.0, 1.0)
    s = P.sum(axis=1, keepdims=True)
    s[s == 0] = 1.0
    return P / s


# ----------------------------
# ArviZ/PyMC extraction
# ----------------------------
def flatten_draws(arr: np.ndarray) -> np.ndarray:
    """
    Flatten (chain, draw, ...) -> (chain*draw, ...).
    """
    arr = np.asarray(arr)
    if arr.ndim >= 3:
        return arr.reshape(-1, *arr.shape[2:])
    if arr.ndim == 2 and arr.shape[0] == 1:
        return arr.reshape(-1)
    return arr


def get_posterior_array(idata, var: str) -> np.ndarray:
    if "posterior" not in idata.groups():
        raise ValueError("InferenceData has no posterior group.")
    if var not in idata.posterior.data_vars:
        raise KeyError(f"Missing posterior variable '{var}'. Available: {list(idata.posterior.data_vars)}")
    return flatten_draws(idata.posterior[var].values)


def find_nc_file(folder: Path) -> Path:
    """
    Prefer stable name bayesian_sem_inference_data.nc, else fallback to first .nc.
    """
    preferred = folder / "bayesian_sem_inference_data.nc"
    if preferred.exists():
        return preferred
    nc = sorted(folder.glob("*.nc"))
    if not nc:
        raise FileNotFoundError(f"No .nc found in {folder}")
    return nc[0]


def align_to_min_draws(**arrays):
    lengths = {k: v.shape[0] for k, v in arrays.items()}
    n_min = min(lengths.values())
    if len(set(lengths.values())) > 1:
        print("⚠️ Draw mismatch; truncating to min draws:", n_min)
        for k, L in lengths.items():
            print(f"   - {k}: {L} -> {n_min}")
    return n_min, {k: v[:n_min] for k, v in arrays.items()}


# ----------------------------
# Name extraction from processed_data.pkl
# ----------------------------
def _try_extract_columns(obj, key: str):
    """
    Try to extract df columns from either:
      - dict-like with obj[key]
      - dataclass / object with attribute key
    """
    if isinstance(obj, dict) and key in obj:
        df = obj[key]
        if hasattr(df, "columns"):
            return list(df.columns)
    if hasattr(obj, key):
        df = getattr(obj, key)
        if hasattr(df, "columns"):
            return list(df.columns)
    return None


def load_dummy_names_from_processed(processed_pkl: Path):
    """
    Returns (handledag_names, age_names) or (None, None) if cannot load.
    """
    if not processed_pkl.exists():
        return None, None

    try:
        with open(processed_pkl, "rb") as f:
            obj = pickle.load(f)
    except Exception as e:
        print(f"⚠️ Could not load processed_data.pkl: {processed_pkl} -> {e}")
        return None, None

    handledag_cols = _try_extract_columns(obj, "handledag_dummies")
    age_cols = _try_extract_columns(obj, "age_dummies")

    # Clean prefixes for readability (optional)
    def clean(cols):
        if cols is None:
            return None
        out = []
        for c in cols:
            c = str(c)
            c = c.replace("handledag_", "")
            c = c.replace("age_", "")
            out.append(c)
        return out

    return clean(handledag_cols), clean(age_cols)


def ensure_names(names, k, prefix):
    """
    If names missing or wrong length, return autogenerated names.
    """
    if names is None or len(names) == 0:
        return [f"{prefix}_{i}" for i in range(k)]
    if len(names) != k:
        print(f"⚠️ {prefix}_names length {len(names)} != {k}. Using autogenerated names.")
        return [f"{prefix}_{i}" for i in range(k)]
    return names


# ----------------------------
# Marginal effects
# ----------------------------
def summarize_effects(effects: np.ndarray) -> dict:
    effects = np.asarray(effects).reshape(-1)
    return {
        "mean_effect": float(np.mean(effects)),
        "hdi_2.5": float(np.quantile(effects, 0.025)),
        "hdi_97.5": float(np.quantile(effects, 0.975)),
        "prob_positive": float(np.mean(effects > 0)),
        "prob_negative": float(np.mean(effects < 0)),
    }


def compute_me_rows(scenario, var_group, var_name, beta_draws, cutpoints, eta0, category_labels, step):
    beta_draws = np.asarray(beta_draws).reshape(-1)
    eta1 = eta0 + step * beta_draws
    p0 = ordered_logit_probs(cutpoints, eta0)
    p1 = ordered_logit_probs(cutpoints, eta1)
    dP = p1 - p0

    rows = []
    for k, lab in enumerate(category_labels):
        summ = summarize_effects(dP[:, k])
        rows.append({
            "scenario": scenario,
            "var_group": var_group,
            "var_name": var_name,
            "category": lab,
            **summ
        })
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base_dir", required=True, help="Appendix folder containing PS0_baseline etc.")
    ap.add_argument("--output_dir", required=True, help="Output folder for marginal effects tables.")
    ap.add_argument("--scenarios", nargs="+", default=[
        "PS0_baseline",
        "PS1_tighter_structural",
        "PS2_wider_structural",
        "PS3_measurement_variance_sensitive"
    ])

    ap.add_argument("--category_labels", nargs="+", default=["NoEquip", "Basket", "Cart", "Trolley"])
    ap.add_argument("--factor_names", nargs="+", default=["brand", "hedonic", "confused", "perf", "careless", "habit", "novelty", "value"])

    # Optional: manual overrides (only used if processed_data.pkl fails or --prefer_processed_names=False)
    ap.add_argument("--handledag_names", nargs="*", default=[])
    ap.add_argument("--age_names", nargs="*", default=[])

    ap.add_argument("--prefer_processed_names", action="store_true", default=True,
                    help="Prefer handledag/age names from processed_data.pkl if available (default True).")

    ap.add_argument("--baseline_eta", type=float, default=0.0)
    ap.add_argument("--factor_step", type=float, default=1.0)
    ap.add_argument("--dummy_step", type=float, default=1.0)

    args = ap.parse_args()

    base_dir = Path(args.base_dir).expanduser().resolve()
    out_dir = Path(args.output_dir).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    if len(args.category_labels) != 4:
        raise SystemExit("category_labels must have exactly 4 labels (4 categories).")

    all_dfs = []

    for scen in args.scenarios:
        scen_dir = base_dir / scen
        if not scen_dir.exists():
            raise SystemExit(f"Scenario folder not found: {scen_dir}")

        nc_path = find_nc_file(scen_dir)
        print(f"\n=== {scen} ===")
        print("Loading:", nc_path)

        idata = az.from_netcdf(nc_path)

        cutpoints = get_posterior_array(idata, "cutpoints")
        if cutpoints.ndim != 2 or cutpoints.shape[1] != 3:
            raise SystemExit(f"cutpoints shape {cutpoints.shape} invalid; expected (n_draws, 3)")

        beta_factors = get_posterior_array(idata, "beta_factors")
        beta_gender = get_posterior_array(idata, "beta_gender").reshape(-1)
        beta_handledag = get_posterior_array(idata, "beta_handledag")
        beta_age = get_posterior_array(idata, "beta_age")

        if beta_factors.ndim != 2:
            raise SystemExit(f"beta_factors must be 2D, got {beta_factors.shape}")
        if beta_handledag.ndim != 2:
            raise SystemExit(f"beta_handledag must be 2D, got {beta_handledag.shape}")
        if beta_age.ndim != 2:
            raise SystemExit(f"beta_age must be 2D, got {beta_age.shape}")

        # --- Names: try processed_data.pkl first ---
        handledag_names = None
        age_names = None

        processed_pkl = scen_dir / "processed_data.pkl"
        if args.prefer_processed_names and processed_pkl.exists():
            h_cols, a_cols = load_dummy_names_from_processed(processed_pkl)
            handledag_names = h_cols
            age_names = a_cols

        # fallback: manual overrides if provided
        if handledag_names is None or len(handledag_names) == 0:
            handledag_names = args.handledag_names if args.handledag_names else None
        if age_names is None or len(age_names) == 0:
            age_names = args.age_names if args.age_names else None

        # ensure correct lengths (otherwise auto-generate)
        factor_names = ensure_names(args.factor_names, beta_factors.shape[1], "factor")
        handledag_names = ensure_names(handledag_names, beta_handledag.shape[1], "handledag")
        age_names = ensure_names(age_names, beta_age.shape[1], "age")

        # align draws
        n_draws, aligned = align_to_min_draws(
            cutpoints=cutpoints,
            beta_factors=beta_factors,
            beta_gender=beta_gender,
            beta_handledag=beta_handledag,
            beta_age=beta_age,
        )
        cutpoints = aligned["cutpoints"]
        beta_factors = aligned["beta_factors"]
        beta_gender = aligned["beta_gender"]
        beta_handledag = aligned["beta_handledag"]
        beta_age = aligned["beta_age"]

        eta0 = np.full(n_draws, float(args.baseline_eta))

        rows = []

        # factors (+factor_step)
        for j, nm in enumerate(factor_names):
            rows += compute_me_rows(scen, "factor", nm, beta_factors[:, j], cutpoints, eta0, args.category_labels, float(args.factor_step))

        # gender dummy (+dummy_step)
        rows += compute_me_rows(scen, "gender", "female", beta_gender, cutpoints, eta0, args.category_labels, float(args.dummy_step))

        # handledag dummies
        for j, nm in enumerate(handledag_names):
            rows += compute_me_rows(scen, "handledag", nm, beta_handledag[:, j], cutpoints, eta0, args.category_labels, float(args.dummy_step))

        # age dummies
        for j, nm in enumerate(age_names):
            rows += compute_me_rows(scen, "age", nm, beta_age[:, j], cutpoints, eta0, args.category_labels, float(args.dummy_step))

        df = pd.DataFrame(rows)

        out_path = out_dir / f"marginal_effects_long_{scen}.csv"
        df.to_csv(out_path, index=False)
        print(f"Saved: {out_path} (rows={len(df)})")

        all_dfs.append(df)

    df_all = pd.concat(all_dfs, ignore_index=True)
    out_all = out_dir / "marginal_effects_long_all_scenarios.csv"
    df_all.to_csv(out_all, index=False)
    print(f"\nSaved combined: {out_all} (rows={len(df_all)})")


if __name__ == "__main__":
    main()